// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Exercise struct {
	Question string `json:"question"`
	Hint     string `json:"hint"`
	Answer   string `json:"answer"`
}
